### PR TITLE
Fix v0.7.0 release.

### PR DESCRIPTION
**Pull request by dkinzer**
The release is breaking do to dependency issues.

This change upgrades the airflow package and some of it's dependencies
in order to resolve the issue.

### CODE REVIEW

**Review by sensei100 — COMMENTED** [review]
@dkinzer Are both and werkzeug part of apache-airflow?  I'm just curious why we are removing them.

**Comment by dkinzer** [comment]
argh... tests passing locally but failing on CI 🙄 ... I'll look into this after lunch.

@sensei100 werkzeug I think is an apache-airflow dep... I'll want to control this all from the ansible-playbook-airflow but will need to see what happens there first before we pin it here...

**Comment by dkinzer** [comment]
I just realized that we can control all our deps via tulflow 😳

**Comment by dkinzer** [comment]
OK, once this is merged this draft release can be published: https://github.com/tulibraries/tulflow/releases/tag/untagged-7e992d7ab02022a4b515

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
